manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: jaschenb
      url-base: https://github.com/jaschenb
  projects:
    - name: zmk
      remote: jaschenb
      revision: mouse-3.2
      import: app/west.yml
  self:
    path: config
